### ISSUE TITLE
Изменять текст при наведении

### ISSUE THREAD

**Issue by sashayakovlev** [Careba/landing#3]
При наведении на каждый из логотипов http://take.ms/cQqTe снизу появляется своя цитата из статьи. При нажатии – переход на сайт.

**Comment by barbatus** [comment]
@sashayakovlev А где тест брать? Для Яндекса - есть, для остальных не нашел.

**Comment by sashayakovlev** [comment]
А, забыл написать. Давай уберем вообще цитаты и оставим просто логотипы не нажимабедльные

**Comment by sashayakovlev** [comment]
А как тут ишью переоткрыть? 
Давай логотипы делать не кликабельными и без ховеров. B можно их чуть разрядить по горизонтали

**Comment by barbatus** [comment]
В базовой версии вроде как переоткрыть может только тот, кто закрыл.
Кстати, слышал, что появилось Trello for Business с новыми фичами вроде интеграции с github. Можно в эту сторону посмотреть.
